# Generated by Django 5.1.7 on 2025-04-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='time_diff',
            field=models.CharField(default='default time', max_length=1000),
        ),
        migrations.AddField(
            model_name='comment',
            name='time_diff',
            field=models.CharField(default='default time', max_length=1000),
        ),
    ]
